/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: FrancescoMilanese (https://sketchfab.com/FrancescoMilanese)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/models/944b590d17c84f2da2c84a6f6ffa3a7c
title: Brass Knuckles
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/brass_kuckles.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["BRASS-KNUCKLES_0"].geometry}
          material={materials["BRASS-KNUCKLES"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/brass_kuckles.gltf");
